### ISSUE TITLE
KeyError: 'category'

### ISSUE THREAD

**Issue by w5688414** [touchsunshine/convert_bdd100k_to_coco_format#2]
I use the py file,bu I got an error
`eric@eric-ms-7a54:~/Documents/convert_bdd100k_to_coco_format$ python convert_to_coco_format.py --src /home/eric/data/deepdrive/bdd100k/labels/bdd100k_labels_images_train.json --dst save.json --dir /home/eric/data/deepdrive/bdd100k/images/100k/train/
it is make_coco_images.......
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]100.00%
Done
it is make_coco_annotations.....
Traceback (most recent call last):-----------------]0.00%
  File "convert_to_coco_format.py", line 135, in <module>
    main(args)
  File "convert_to_coco_format.py", line 131, in main
    convert_coco(args)
  File "convert_to_coco_format.py", line 124, in convert_coco
    allInfo['annotations'] = make_coco_annotations(src)
  File "convert_to_coco_format.py", line 100, in make_coco_annotations
    category = anno['category']
KeyError: 'category'
`
how can I solve this problem

**Comment by hzhang33BEI** [comment]
i have fix the README,please follow the new README

**Comment by hzhang33BEI** [comment]
> I use the py file,bu I got an error
> `eric@eric-ms-7a54:~/Documents/convert_bdd100k_to_coco_format$ python convert_to_coco_format.py --src /home/eric/data/deepdrive/bdd100k/labels/bdd100k_labels_images_train.json --dst save.json --dir /home/eric/data/deepdrive/bdd100k/images/100k/train/ it is make_coco_images....... [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]100.00% Done it is make_coco_annotations..... Traceback (most recent call last):-----------------]0.00% File "convert_to_coco_format.py", line 135, in <module> main(args) File "convert_to_coco_format.py", line 131, in main convert_coco(args) File "convert_to_coco_format.py", line 124, in convert_coco allInfo['annotations'] = make_coco_annotations(src) File "convert_to_coco_format.py", line 100, in make_coco_annotations category = anno['category'] KeyError: 'category'`
> how can I solve this problem

i have fix the README,please follow the new README

**Comment by w5688414** [comment]
it seems that we have different format, and my val.json format example is 
`[
    {
        "name": "b1c66a42-6f7d68ca.jpg",
        "attributes": {
            "weather": "overcast",
            "scene": "city street",
            "timeofday": "daytime"
        },
        "timestamp": 10000,
        "labels": [
            {
                "category": "traffic sign",
                "attributes": {
                    "occluded": false,
                    "truncated": false,
                    "trafficLightColor": "none"
                },
                "manualShape": true,
                "manualAttributes": true,
                "box2d": {
                    "x1": 1000.698742,
                    "y1": 281.992415,
                    "x2": 1040.626872,
                      .....

**Comment by monjurulkarim** [comment]
@w5688414 how did you solve this? I am still having the KeyError:'category' problem.
