### ISSUE TITLE
category

### ISSUE THREAD

**Issue by Linstancy** [touchsunshine/convert_bdd100k_to_coco_format#4]
hi， when I use py file, I also meet with the KEYERROR: 'category'. I look up your new ReadMe, byt I do not find some useful information. How can I solve this problem? Could you give some guidance?
 Thanks a lot!

**Comment by Linstancy** [comment]
ok I am sorry for not reading ReadMe carefully. Now, I have convert bdd detection file into coco format, but I want to know whether this bdd_coco format can be applied for object segmentaiton task, or it is only adaptive for detection?
Thanks a lot!

**Comment by monjurulkarim** [comment]
@Linstancy how did you solve this? I am still having the KeyError:'category' problem.

**Comment by Linstancy** [comment]
I also failed to convert.



发自我的iPhone


------------------ Original ------------------
